language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
sudo: false
install:
  - wget -q -O - https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz | tar xvz
  - linux-amd64/glide install
script:
  - make test-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
